#!/usr/bin/env python3
"""Export a v21 AutoDL package for narrow res_mlp DL search."""
from __future__ import annotations

import argparse
import hashlib
import json
import shutil
import tarfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import pandas as pd


ROOT = Path("/home/zdq-as/mouse_methyl_work")
DEFAULT_MATRIX = ROOT / "results" / "multidataset_v8_3_ablation" / "all6" / "all_rrbs_region_matrix_5kb.parquet"
DEFAULT_METADATA = ROOT / "metadata" / "model_sample_metadata_v8.csv"
DEFAULT_OUT = ROOT / "results" / "ralph_v21_raid_raw_clock" / "autodl_package"
DATASETS = ["GSE120137", "GSE80672", "GSE93957", "GSE121141", "GSE60012", "GSE213628"]


REMOTE_RUNNER = r'''#!/usr/bin/env python3
"""Remote v21 AutoDL narrow res_mlp runner generated by export_v21_autodl_package.py."""
from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[2]
TRAIN = ROOT / "scripts" / "train" / "train_deep_clock.py"
OUT = ROOT / "results" / "autoresearch_v21_deep_learning"
DATASETS = ["GSE120137", "GSE80672", "GSE93957", "GSE121141", "GSE60012", "GSE213628"]


def run(cmd: list[str]) -> None:
    print(" ".join(cmd), flush=True)
    subprocess.run(cmd, cwd=str(ROOT), check=True)


def load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def base_cmd(config: dict, out_dir: Path, eval_mode: str, heldout_dataset: str | None = None, randomize: bool = False) -> list[str]:
    manifest = load_json(ROOT / "v21_autodl_manifest.json")
    cmd = [
        "uv", "run", "--extra", "dl", "python", str(TRAIN),
        "--matrix_path", str(ROOT / manifest["matrix_package_path"]),
        "--metadata_path", str(ROOT / manifest["metadata_package_path"]),
        "--output_dir", str(out_dir),
        "--eval_mode", eval_mode,
        "--architecture", "res_mlp",
        "--n_feature_prefilter", str(config["n_feature_prefilter"]),
        "--imputation", "median",
        "--preprocess", str(config["preprocess"]),
        "--width", str(config["width"]),
        "--depth", str(config["depth"]),
        "--dropout", str(config["dropout"]),
        "--lr", str(config["lr"]),
        "--bottleneck", "64",
        "--epochs", "300",
        "--patience", "30",
        "--batch_size", "64",
        "--weight_decay", "0.001",
        "--huber_beta", "0.5",
        "--amp",
    ]
    if heldout_dataset:
        cmd.extend(["--heldout_dataset", heldout_dataset])
    if randomize:
        cmd.append("--randomize_labels")
    return cmd


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    configs = pd.read_csv(ROOT / "v21_autodl_config_manifest.csv").to_dict(orient="records")
    summary_rows = []
    for config in configs:
        config_id = str(config["config_id"])
        out_dir = OUT / "groupkfold" / config_id
        result_path = out_dir / "result.json"
        if not result_path.exists():
            run(base_cmd(config, out_dir, "groupkfold"))
        result = load_json(result_path)
        summary_rows.append({"config_id": config_id, **config, **result})
    summary = pd.DataFrame(summary_rows).sort_values(["mae_weeks", "rmse_weeks"], ascending=True)
    summary.to_csv(OUT / "v21_dl_summary.csv", index=False)
    (OUT / "v21_dl_summary.json").write_text(summary.to_json(orient="records", indent=2), encoding="utf-8")

    top = summary.head(3)["config_id"].tolist()
    lodo_rows = []
    by_id = {str(row["config_id"]): row for row in configs}
    for config_id in top:
        config = by_id[config_id]
        for dataset in DATASETS:
            out_dir = OUT / "lodo" / config_id / dataset
            result_path = out_dir / "result.json"
            if not result_path.exists():
                run(base_cmd(config, out_dir, "heldout", heldout_dataset=dataset))
            result = load_json(result_path)
            lodo_rows.append({"config_id": config_id, "dataset": dataset, **result})
    pd.DataFrame(lodo_rows).to_csv(OUT / "v21_lodo_summary.csv", index=False)

    if top:
        best = by_id[top[0]]
        sanity_dir = OUT / "random_label_sanity" / top[0]
        if not (sanity_dir / "result.json").exists():
            run(base_cmd(best, sanity_dir, "groupkfold", randomize=True))
        final_dir = OUT / "final_all_data_model"
        if not (final_dir / "result.json").exists():
            run(base_cmd(best, final_dir, "final"))

    print(f"v21 AutoDL results saved to {OUT}")


if __name__ == "__main__":
    main()
'''


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def write_json(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True, default=str), encoding="utf-8")


def copy_file(src: Path, dst: Path, dry_run: bool) -> dict[str, Any]:
    row = {"source": str(src), "target": str(dst), "exists": src.exists(), "size_bytes": src.stat().st_size if src.exists() else 0}
    if src.exists():
        row["sha256"] = sha256(src)
    if not dry_run:
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)
    return row


def candidate_configs() -> pd.DataFrame:
    rows = []
    idx = 1
    for top in ["500", "1000", "2000"]:
        for preprocess in ["standard", "robust", "quantile_uniform"]:
            for depth in [3, 4]:
                config_id = f"v21_res_mlp_top{top}_{preprocess}_w256_d{depth}_do0p1_lr0p0003"
                rows.append(
                    {
                        "config_id": config_id,
                        "architecture": "res_mlp",
                        "n_feature_prefilter": top,
                        "preprocess": preprocess,
                        "width": 256,
                        "depth": depth,
                        "dropout": 0.1,
                        "lr": 0.0003,
                        "rank": idx,
                    }
                )
                idx += 1
    return pd.DataFrame(rows)


def make_tar(package_dir: Path, tar_path: Path) -> None:
    tar_path.parent.mkdir(parents=True, exist_ok=True)
    with tarfile.open(tar_path, "w:gz") as tar:
        tar.add(package_dir, arcname=package_dir.name)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--matrix", type=Path, default=DEFAULT_MATRIX)
    parser.add_argument("--metadata", type=Path, default=DEFAULT_METADATA)
    parser.add_argument("--out-dir", type=Path, default=DEFAULT_OUT)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    package_dir = args.out_dir / "v21_autodl_package"
    data_dir = package_dir / "data"
    scripts_dir = package_dir / "scripts"
    train_dir = scripts_dir / "train"
    validate_dir = scripts_dir / "validate"
    copied = []

    if not args.dry_run:
        if package_dir.exists():
            shutil.rmtree(package_dir)
        train_dir.mkdir(parents=True, exist_ok=True)
        validate_dir.mkdir(parents=True, exist_ok=True)
        data_dir.mkdir(parents=True, exist_ok=True)

    matrix_target = data_dir / args.matrix.name
    metadata_target = data_dir / args.metadata.name
    copied.append(copy_file(args.matrix, matrix_target, args.dry_run))
    copied.append(copy_file(args.metadata, metadata_target, args.dry_run))
    for rel_path in [
        "pyproject.toml",
        "uv.lock",
        "scripts/train/train_deep_clock.py",
        "scripts/validate/benchmark_metrics.py",
    ]:
        src = ROOT / rel_path
        dst = package_dir / rel_path
        copied.append(copy_file(src, dst, args.dry_run))

    configs = candidate_configs()
    manifest = {
        "timestamp": utc_now(),
        "package": "v21_autodl_res_mlp_narrow",
        "matrix_source": str(args.matrix),
        "metadata_source": str(args.metadata),
        "matrix_package_path": str(matrix_target.relative_to(package_dir)),
        "metadata_package_path": str(metadata_target.relative_to(package_dir)),
        "config_manifest": "v21_autodl_config_manifest.csv",
        "remote_runner": "scripts/train/run_v21_autodl_res_mlp_narrow.py",
        "remote_command": "bash run_v21_autodl.sh",
        "datasets_for_lodo": DATASETS,
        "dl_scope": "AutoDL only; res_mlp narrow search centered on v20 best.",
        "local_training_authorized": False,
        "autoresearch_authorized": False,
        "copied_files": copied,
    }

    if not args.dry_run:
        configs.to_csv(package_dir / "v21_autodl_config_manifest.csv", index=False)
        (train_dir / "run_v21_autodl_res_mlp_narrow.py").write_text(REMOTE_RUNNER, encoding="utf-8")
        (package_dir / "run_v21_autodl.sh").write_text(
            "#!/usr/bin/env bash\nset -euo pipefail\nuv run --extra dl python scripts/train/run_v21_autodl_res_mlp_narrow.py\n",
            encoding="utf-8",
        )
        write_json(package_dir / "v21_autodl_manifest.json", manifest)
        tar_path = args.out_dir / "v21_autodl_package.tgz"
        make_tar(package_dir, tar_path)
        manifest["tar_path"] = str(tar_path)
        write_json(args.out_dir / "v21_autodl_export_manifest.json", manifest)
    else:
        args.out_dir.mkdir(parents=True, exist_ok=True)
        configs.to_csv(args.out_dir / "v21_autodl_config_manifest.dry_run.csv", index=False)
        write_json(args.out_dir / "v21_autodl_export_manifest.dry_run.json", manifest)

    print(json.dumps(manifest, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
